language: node_js
cache: yarn
node_js:
  - '8.9.3'
os:
  - linux
dist: trusty
before_install:
  - whoami
  - node -v
  - yarn -v
install:
  - apt-get update && apt-get install -y libgtk2.0-0 libgtk-3-0 libgconf-2-4 libasound2 libxtst6 libxss1 libnss3 xvfb hunspell-en-us
  - yarn install --frozen-lockfile
script:
  - yarn generate
  - Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
  - export DISPLAY=:9.0
  - export LC_ALL=en_US
  - yarn test
env:
  global:
    - SIGNAL_ENV: production
sudo: false
notifications:
  email: false
