name: 'Deduplicate check'
description: 'Deduplicate check'
runs:
  using: 'composite'
  steps:
    - name: Enforce yarn.lock has no duplicates
      shell: bash
      if: runner.os == 'Linux'
      run: yarn yarn-deduplicate yarn.lock --fail
